# Generated by Django 2.0.1 on 2018-01-25 07:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('priority', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('0', 'Created'), ('1', 'In Progress'), ('2', 'Completed'), ('3', 'Rejected')], default=0, max_length=1)),
                ('target_date', models.DateField(verbose_name='date targetted')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2018, 1, 25, 12, 35, 39, 940806))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc.Client')),
            ],
        ),
        migrations.CreateModel(
            name='ProductArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='product_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poc.ProductArea'),
        ),
    ]
